/**
 * Add 20 fictitious campaigns to Firestore
 * Run with: npx tsx scripts/seedTwentyCampaigns.ts
 */

import { config } from "dotenv";
config();

import { initializeApp } from "firebase/app";
import { getFirestore, collection, doc, setDoc, serverTimestamp, Timestamp } from "firebase/firestore";
import type { Campaign } from "../lib/data";

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

const twentyCampaigns: Omit<Campaign, "id">[] = [
  {
    title: "Clean Water Wells for San Pedro",
    description: "Building community wells to provide safe drinking water for families in San Pedro Ambergris Caye.",
    fullDescription: "Many residents still rely on rainwater or expensive bottled water. We aim to drill and maintain community wells so every family has access to clean, safe drinking water. Local partners will manage maintenance.",
    creator: "San Pedro Water Initiative",
    creatorType: "organization",
    goal: 5000,
    raised: 2560,
    backers: 89,
    daysLeft: 22,
    category: "Community",
    image: "https://picsum.photos/seed/water1/800/600",
    location: "San Pedro, Ambergris Caye",
    createdAt: "2026-02-01",
    verified: true,
  },
  {
    title: "Prosthetic Limb for Pedro",
    description: "Helping Pedro afford a prosthetic leg after a workplace accident so he can return to providing for his family.",
    fullDescription: "Pedro lost his leg in an industrial accident. Insurance has run out and he cannot afford the prosthetic needed to walk and work again. His family depends on his income. Your support will change his life.",
    creator: "Pedro Martinez",
    creatorType: "individual",
    goal: 5000,
    raised: 2610,
    backers: 156,
    daysLeft: 14,
    category: "Medical",
    image: "https://picsum.photos/seed/medical3/800/600",
    location: "Belize City, Belize",
    createdAt: "2026-02-08",
    verified: true,
  },
  {
    title: "Music Program for Belize City Youth",
    description: "Instruments and lessons for 50+ at-risk youth to learn music and build confidence.",
    fullDescription: "We run an after-school music program but lack instruments and qualified teachers. Funds will buy guitars, keyboards, and drums and pay for instructors. Music changes lives—help us reach more kids.",
    creator: "Belize Youth Arts Collective",
    creatorType: "charity",
    goal: 3500,
    raised: 1510,
    backers: 62,
    daysLeft: 28,
    category: "Education",
    image: "https://picsum.photos/seed/music1/800/600",
    location: "Belize City, Belize",
    createdAt: "2026-01-25",
    verified: true,
  },
  {
    title: "Flood Recovery in Cayo Villages",
    description: "Repairing roads and homes in Cayo District villages hit by severe flooding.",
    fullDescription: "Recent floods damaged homes, roads, and crops. Families need materials to repair roofs and walls, and communities need help clearing and fixing access roads. Every dollar goes to affected families.",
    creator: "Cayo Flood Relief Fund",
    creatorType: "organization",
    goal: 5000,
    raised: 3150,
    backers: 201,
    daysLeft: 10,
    category: "Disaster Relief",
    image: "https://picsum.photos/seed/flood1/800/600",
    location: "Cayo District, Belize",
    createdAt: "2026-02-10",
    verified: true,
  },
  {
    title: "Dialysis Treatment for Elena",
    description: "Covering one year of dialysis sessions for Elena while she waits for a kidney transplant.",
    fullDescription: "Elena was diagnosed with kidney failure. She needs dialysis three times a week to stay alive. Her family cannot afford the full cost. We are raising funds to cover her treatments until she can receive a transplant.",
    creator: "Elena's Family",
    creatorType: "individual",
    goal: 5000,
    raised: 2540,
    backers: 178,
    daysLeft: 16,
    category: "Medical",
    image: "https://picsum.photos/seed/medical4/800/600",
    location: "Orange Walk Town, Belize",
    createdAt: "2026-02-06",
    verified: true,
  },
  {
    title: "Library Books for Punta Gorda Schools",
    description: "New books and shelves for three primary school libraries in Toledo District.",
    fullDescription: "School libraries are empty or outdated. We want to stock them with age-appropriate books in English and Spanish so children can develop a love of reading. Teachers have provided wish lists.",
    creator: "Toledo Education Trust",
    creatorType: "charity",
    goal: 2800,
    raised: 1420,
    backers: 54,
    daysLeft: 31,
    category: "Education",
    image: "https://picsum.photos/seed/books1/800/600",
    location: "Punta Gorda, Toledo",
    createdAt: "2026-01-20",
    verified: true,
  },
  {
    title: "Funeral Costs for the Reyes Family",
    description: "Helping the Reyes family give their father a dignified burial after his sudden passing.",
    fullDescription: "Mr. Reyes passed away unexpectedly. His family is struggling to cover funeral and burial costs. We are asking the community to help so they can say goodbye with peace and dignity.",
    creator: "Reyes Family",
    creatorType: "individual",
    goal: 5000,
    raised: 3200,
    backers: 71,
    daysLeft: 7,
    category: "Emergency",
    image: "https://picsum.photos/seed/funeral1/800/600",
    location: "Belmopan, Belize",
    createdAt: "2026-02-14",
    verified: true,
  },
  {
    title: "Solar Lights for Rural Toledo",
    description: "Solar-powered lights for 100 households without electricity in remote Toledo villages.",
    fullDescription: "Many families study and work by candle or kerosene. Solar lights are safe, clean, and long-lasting. We will distribute lights and train families on use and basic maintenance.",
    creator: "Belize Green Energy Project",
    creatorType: "organization",
    goal: 4500,
    raised: 2510,
    backers: 93,
    daysLeft: 19,
    category: "Community",
    image: "https://picsum.photos/seed/solar1/800/600",
    location: "Toledo District, Belize",
    createdAt: "2026-02-03",
    verified: true,
  },
  {
    title: "Cancer Treatment for Little Ana",
    description: "Funding chemotherapy and travel for 6-year-old Ana's cancer treatment abroad.",
    fullDescription: "Ana was diagnosed with leukemia. She needs treatment not fully available in Belize. Funds will cover chemotherapy, travel to the specialist center, and accommodation for her mother during treatment.",
    creator: "Ana's Parents",
    creatorType: "individual",
    goal: 5000,
    raised: 2460,
    backers: 312,
    daysLeft: 11,
    category: "Medical",
    image: "https://picsum.photos/seed/medical5/800/600",
    location: "Dangriga, Belize",
    createdAt: "2026-02-09",
    verified: true,
  },
  {
    title: "Fishermen Boat Repair After Storm",
    description: "Repairing and replacing fishing boats and gear for coastal families after a severe storm.",
    fullDescription: "A sudden storm destroyed or damaged many small fishing boats. Without them, families have no income. We are raising funds to repair boats and replace nets and engines so fishermen can work again.",
    creator: "Coastal Fishermen Association",
    creatorType: "organization",
    goal: 5000,
    raised: 2700,
    backers: 134,
    daysLeft: 20,
    category: "Disaster Relief",
    image: "https://picsum.photos/seed/boat1/800/600",
    location: "Placencia, Belize",
    createdAt: "2026-02-02",
    verified: true,
  },
  {
    title: "Scholarship Fund for Single Mothers",
    description: "Tuition and books for 15 single mothers to complete vocational or tertiary education.",
    fullDescription: "We support single mothers who want to finish school or learn a trade. Funds cover tuition, books, and a small stipend for childcare so they can attend classes. Education is the way out of poverty.",
    creator: "Belize Women's Advancement",
    creatorType: "charity",
    goal: 5000,
    raised: 2600,
    backers: 98,
    daysLeft: 25,
    category: "Education",
    image: "https://picsum.photos/seed/scholarship1/800/600",
    location: "Belize City, Belize",
    createdAt: "2026-01-29",
    verified: true,
  },
  {
    title: "Emergency Roof Repair for Elderly Couple",
    description: "Replacing a collapsed roof for an elderly couple in Corozal so they can stay in their home.",
    fullDescription: "Their roof caved in after heavy rains. They have nowhere else to go and cannot afford repairs. We want to rebuild the roof and make the home safe so they can live with dignity.",
    creator: "Corozal Community Help",
    creatorType: "organization",
    goal: 3500,
    raised: 1970,
    backers: 67,
    daysLeft: 13,
    category: "Emergency",
    image: "https://picsum.photos/seed/roof1/800/600",
    location: "Corozal Town, Belize",
    createdAt: "2026-02-11",
    verified: true,
  },
  {
    title: "Veterinary Care for Village Livestock",
    description: "Mobile vet clinic and vaccines for farmers' animals in rural Stann Creek and Cayo.",
    fullDescription: "Farmers often lose animals to preventable diseases because vets are far away and expensive. We will run monthly mobile clinics and provide vaccines and basic care to protect their livelihoods.",
    creator: "Belize Livestock Health Initiative",
    creatorType: "charity",
    goal: 4000,
    raised: 1890,
    backers: 58,
    daysLeft: 27,
    category: "Community",
    image: "https://picsum.photos/seed/vet1/800/600",
    location: "Stann Creek, Belize",
    createdAt: "2026-01-27",
    verified: true,
  },
  {
    title: "Surgery for Miguel's Spine",
    description: "Spinal surgery so Miguel can walk again after a construction site fall.",
    fullDescription: "Miguel fell from scaffolding and damaged his spine. Without surgery he may never walk again. His employer's insurance has denied the claim. We are raising funds for the operation and rehabilitation.",
    creator: "Miguel's Family",
    creatorType: "individual",
    goal: 5000,
    raised: 2800,
    backers: 245,
    daysLeft: 9,
    category: "Medical",
    image: "https://picsum.photos/seed/medical6/800/600",
    location: "San Ignacio, Cayo",
    createdAt: "2026-02-12",
    verified: true,
  },
  {
    title: "School Uniforms for 200 Kids",
    description: "New uniforms and shoes for children who cannot afford them so they can attend school.",
    fullDescription: "Many children miss school because they don't have uniforms. We partner with schools to provide uniforms and shoes to families in need. Every child deserves to go to school without shame.",
    creator: "Uniforms for All",
    creatorType: "charity",
    goal: 3500,
    raised: 1600,
    backers: 82,
    daysLeft: 24,
    category: "Education",
    image: "https://picsum.photos/seed/uniforms1/800/600",
    location: "Nationwide, Belize",
    createdAt: "2026-02-04",
    verified: true,
  },
  {
    title: "Fire Truck for Volunteer Fire Brigade",
    description: "A secondhand fire truck and basic equipment for a volunteer fire brigade in Orange Walk.",
    fullDescription: "The town's volunteer firefighters have only one old truck and limited gear. A second truck and updated equipment will help them respond faster and save more lives and property.",
    creator: "Orange Walk Fire Brigade",
    creatorType: "organization",
    goal: 5000,
    raised: 2310,
    backers: 167,
    daysLeft: 18,
    category: "Community",
    image: "https://picsum.photos/seed/fire1/800/600",
    location: "Orange Walk Town, Belize",
    createdAt: "2026-02-01",
    verified: true,
  },
  {
    title: "Baby Formula and Diapers for New Moms",
    description: "Six months of formula and diapers for 20 new mothers in crisis who cannot afford basics.",
    fullDescription: "Some new mothers cannot breastfeed and cannot afford formula. Others struggle to buy diapers. We provide a six-month supply to the neediest families so babies stay healthy and fed.",
    creator: "Belize Baby Fund",
    creatorType: "charity",
    goal: 2800,
    raised: 1260,
    backers: 49,
    daysLeft: 30,
    category: "Emergency",
    image: "https://picsum.photos/seed/baby1/800/600",
    location: "Belize City, Belize",
    createdAt: "2026-01-22",
    verified: true,
  },
  {
    title: "Rebuild After House Fire in Belmopan",
    description: "Rebuilding a family's home after a total loss in a fire; they lost everything.",
    fullDescription: "A family of six lost their home and all belongings in a fire. They are staying with relatives but need help to rebuild. Funds will go to materials and labor to get them back into a safe home.",
    creator: "Belmopan Community Aid",
    creatorType: "organization",
    goal: 5000,
    raised: 2640,
    backers: 156,
    daysLeft: 15,
    category: "Disaster Relief",
    image: "https://picsum.photos/seed/fire2/800/600",
    location: "Belmopan, Belize",
    createdAt: "2026-02-07",
    verified: true,
  },
  {
    title: "Dental Care for 50 Children",
    description: "Free dental check-ups, cleanings, and fillings for children from low-income families.",
    fullDescription: "Many children have never seen a dentist. We partner with volunteer dentists to provide free care in schools and community centers. Good dental health improves overall health and confidence.",
    creator: "Belize Smiles Project",
    creatorType: "charity",
    goal: 3000,
    raised: 1540,
    backers: 61,
    daysLeft: 21,
    category: "Medical",
    image: "https://picsum.photos/seed/dental1/800/600",
    location: "Belize District",
    createdAt: "2026-02-05",
    verified: true,
  },
  {
    title: "Sports Gear for High School Teams",
    description: "Balls, nets, and uniforms for football and basketball teams at three high schools.",
    fullDescription: "Schools want to offer sports but lack equipment. We will provide footballs, basketballs, nets, and team uniforms so students can compete and stay active. Sport builds discipline and teamwork.",
    creator: "Belize School Sports Fund",
    creatorType: "organization",
    goal: 3800,
    raised: 1880,
    backers: 73,
    daysLeft: 26,
    category: "Education",
    image: "https://picsum.photos/seed/sports2/800/600",
    location: "Cayo and Belize District",
    createdAt: "2026-01-30",
    verified: true,
  },
];

async function seedTwentyCampaigns() {
  try {
    console.log("Initializing Firebase...");
    const app = initializeApp(firebaseConfig);
    const db = getFirestore(app);

    // Use same ID naming as original seed: "1"-"8" exist, so use "9" through "28"
    const startId = 9;
    console.log("Adding 20 fictitious campaigns to Firestore (ids 9–28)...\n");
    for (let i = 0; i < twentyCampaigns.length; i++) {
      const campaign = twentyCampaigns[i];
      const id = String(startId + i);
      const campaignRef = doc(db, "campaigns", id);
      await setDoc(campaignRef, {
        ...campaign,
        id,
        createdAt: campaign.createdAt ? Timestamp.fromDate(new Date(campaign.createdAt)) : serverTimestamp(),
        updatedAt: serverTimestamp(),
      });
      console.log(`✓ ${i + 1}/20: [${id}] ${campaign.title}`);
    }

    console.log("\n✅ Done! 20 campaigns added to Firestore.");
    process.exit(0);
  } catch (error: any) {
    console.error("❌ Error:", error);
    process.exit(1);
  }
}

seedTwentyCampaigns();
